# Config file taken from adapting the output of the following command:
# $helm show values nfs-subdir-external-provisioner/nfs-subdir-external-provisioner

replicaCount: 2

storageClass:
  name: nfs
  defaultClass: true
  provisionerName: nfs-provisioner
  accessModes: ReadWriteMany

nfs:
  server: "{{ nfs['host'] }}"
  path: "{{ nfs['path'] }}/{{ nfs['k8s_share_path'] }}"

rbac:
  create: true
