# Config file taken from adapting the output of the following command:
# $helm show values jupyterhub/jupyterhub

hub:
  service:
    type: ClusterIP
  networkPolicy:
    enabled: false
  services:
    papermill:
      admin: true
      #TODO: don't hardcode keys
      apiToken: "ed90e67d5ae1dfa88c811f32251acd49a7fc1a6f114ac998b9601430335f5ef4"
  config:
    Authenticator:
      allowed_users:
      - pedro
      - michel
      - maarten
      - testuser
      - mathias
      - said
      - peter
      - svetlana
      - wouter
      - testuser
      admin_users:
      - pedro
      - michel
      - maarten
    #TODO: better auth method
    DummyAuthenticator:
      password: "1data@UZGent"

proxy:
  service:
    type: NodePort
    nodePorts:
      http: 30314
  chp:
    networkPolicy:
      enabled: false

singleuser:
  cpu:
    limit: 1.0
    guarantee: 0.2
  storage:
    dynamic:
      storageClass: nfs
    extraVolumes:
      - name: data-lake
        persistentVolumeClaim:
          claimName: data-lake-pvc
    extraVolumeMounts:
      - name: data-lake
        mountPath: /data-lake
  networkPolicy:
     enabled: false
  image:
    name: "192.168.200.20:5000/uzg/data-science"
    tag: latest
    pullPolicy: Always
  profileList:
    - display_name: "Data Science"
      description: "Data Science Environment with Tensorflow"
      default: true
      kubespawner_override:
        cmd: ["jupyter-labhub"]
        image_pull_policy: "Always"
    - display_name: "Data Engineering"
      description: "Data Engineering Environment with Pyspark"
      kubespawner_override:
        image: "192.168.200.20:5000/uzg/data-engineering:latest"
        # cmd: ["start-notebook.sh"]
        cmd: ["jupyter-labhub"]
        image_pull_policy: "Always"
  extraEnv: #Force jupyterlab with Git integration
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"

prePuller:
  hook:
    enabled: false
